### ISSUE TITLE
Upgrade framework from v3 to v5 to

### ISSUE THREAD

**Issue by tonygilkerson** [claygilk/ThunderDome#2]
I have v5 on my mac. I don't want to down grade. V3 seems old so I suggest upgrading to v5

**Comment by tonygilkerson** [comment]
@claygilk I just assigned to you. Let me know if you get notified.  Please take a look at the code changes in #3 and merge when you are ready. Once you merge #3 this issue should closed automatically because they are linked (see linked pull requests over on the right)

**Comment by tonygilkerson** [comment]
Strange, at first I thought this was preventing me from build the project but seems like I can build even with this at v3.  IDK v3 seems old, you might need to research this to see if it is a good idea to lag or stay current?

**Comment by claygilk** [comment]
@tonygilkerson So I have to use v. 3.1 for class. They said to use it because it is the 'long term support' version or something like that.  I'm hesitant to upgrade my version to 5, because I don't want to cause issues for myself when I'm doing homework. Do you think that is likely? If so, is there a way to let the user determine which version to run?

**Comment by tonygilkerson** [comment]
@claygilk ok, I will try to get it to work on v3.  I think it is possible.  I did have an issue but it might have been the fact that I had your windows binaries in the project.  If you can do #4 that would be helpful.

**Comment by tonygilkerson** [comment]
we want to keep it at v3. wont do.
